name: Issue Implementation

on:
  issues:
    types: [labeled]

jobs:
  implement:
    if: github.event.label.name == 'validated'
    uses: neil-oliver/.github/.github/workflows/issue-implement-reusable.yml@main
    secrets: inherit
    permissions:
      issues: write
      contents: write
      pull-requests: write
